name: Disney-clone ci pipeline

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]
#on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Nx test | e2e | lint | build
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependencies
      uses: bahmutov/npm-install@HEAD

    - name: Build app
      run: npx nx affected --target=build --base=origin/main --parallel
    
    - name: Test app
      run: npx nx affected --target=test --base=origin/main --parallel
    
    - name: Lint app
      run: npx nx affected --target=lint --base=origin/main --parallel
    
    - name: e2e Test app
      run: npx nx affected --target=e2e --base=origin/main --parallel

    # - name: Build and publish Docker container
    #   uses: mr-smithers-excellent/docker-build-push@v5
    #   with:
    #     image: docker-hub-repo/image-name
    #     registry: docker.io
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
